### ISSUE TITLE
High producer latency

### ISSUE THREAD

**Issue by ducas** [ah-/rdkafka-dotnet#10]
I've written a few test clients in [my RdKafka-Test repo](https://github.com/ducas/rdkafka-test) and have consistently found that the process of publishing messages seems to be quite slow. The following timer output was taken after running the ProducerTest console for a few minutes and shows an average of 122ms and blips up to 422ms.

    ***** Timers - 2016-02-08T05:02:48.9323Z *****
        [ProducerTest] Published
       Active Sessions = 0
                 Count = 107600 Events
            Mean Value = 99.95 Events/s
         1 Minute Rate = 100.00 Events/s
         5 Minute Rate = 99.53 Events/s
        15 Minute Rate = 93.98 Events/s
                 Count = 107600 Events
                  Last = 136.00 ms
                   Min = 3.00 ms
                   Max = 422.00 ms
                  Mean = 122.57 ms
                StdDev = 63.28 ms
                Median = 135.00 ms
                  75% <= 137.00 ms
                  95% <= 236.00 ms
                  98% <= 305.00 ms
                  99% <= 337.00 ms
                99.9% <= 422.00 ms

This is running on my ~1yo fully specced MacBook Pro 15 with Kafka in a Vagrant machine on the host from Windows in a VMWare machine. I tried running up boxes in AWS and had similar results. There is no memory or CPU utilisation pressure in both Windows and Linux.

Any ideas...?

**EDIT** - I had some dodgy code in there dealing with tasks... after removing it things got a little bit better.

**Comment by ah-** [comment]
Hey, those tests are fantastic, I love them!

With slow, you mean latency is high? I believe this is caused by the default config of librdkafka being very much geared towards throughput over latency. See https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md for the knobs you can turn.

Using this config:
```
var topicConfig = new TopicConfig();
topicConfig["request.required.acks"] = "0";
var config = new Config();
config.DefaultTopicConfig = topicConfig;
config["socket.blocking.max.ms"] = "1";
config["queue.buffering.max.ms"] = "1";
using (var publisher = new Producer(config, brokers))
```
and 
```
log.flush.interval.messages=10
log.flush.interval.ms=1
```
on the broker i get these numbers:

```
***** Timers - 2016-02-08T04:49:21.7331Z *****

    [ProducerTest] Published
   Active Sessions = 0
             Count = 28400 Events
        Mean Value = 99.77 Events/s
     1 Minute Rate = 100.36 Events/s
     5 Minute Rate = 92.27 Events/s
    15 Minute Rate = 85.37 Events/s
             Count = 28400 Events
              Last = 12.00 ms
               Min = 0.00 ms
               Max = 16.00 ms
              Mean = 2.70 ms
            StdDev = 1.89 ms
            Median = 2.00 ms
              75% <= 3.00 ms
              95% <= 5.00 ms
              98% <= 10.00 ms
              99% <= 12.00 ms
            99.9% <= 16.00 ms
```
on a slightly older MBP, with Kafka running on osx and ProducerTest in a Windows VM on VMWare.

**Comment by ducas** [comment]
@ah- thanks for the response!

I changed the producer settings and that's definitely made a significant improvement...

    ***** Timers - 2016-02-08T05:30:19.1634Z *****

        [ProducerTest] Published
       Active Sessions = 0
                 Count = 1900 Events
            Mean Value = 94.62 Events/s
         1 Minute Rate = 84.42 Events/s
         5 Minute Rate = 80.98 Events/s
        15 Minute Rate = 80.33 Events/s
                 Count = 1900 Events
                  Last = 35.00 ms
                   Min = 2.00 ms
                   Max = 53.00 ms
                  Mean = 31.13 ms
                StdDev = 15.04 ms
                Median = 35.00 ms
                  75% <= 36.00 ms
                  95% <= 53.00 ms
                  98% <= 53.00 ms
                  99% <= 53.00 ms
                99.9% <= 53.00 ms

It came down a little after changing the server settings, but not to the same extent as yours - 

    ***** Timers - 2016-02-08T05:35:19.4932Z *****

        [ProducerTest] Published
       Active Sessions = 0
                 Count = 4400 Events
            Mean Value = 97.64 Events/s
         1 Minute Rate = 89.73 Events/s
         5 Minute Rate = 82.50 Events/s
        15 Minute Rate = 80.87 Events/s
                 Count = 4400 Events
                  Last = 34.00 ms
                   Min = 2.00 ms
                   Max = 110.00 ms
                  Mean = 27.68 ms
                StdDev = 23.15 ms
                Median = 34.00 ms
                  75% <= 36.00 ms
                  95% <= 53.00 ms
                  98% <= 109.00 ms
                  99% <= 109.00 ms
                99.9% <= 110.00 ms

I'll give this a run on some servers over the next couple days and see how it goes. Thanks again!

**Comment by ah-** [comment]
Cool, let me know if you find anything interesting!
