### ISSUE TITLE
get messages by key

### ISSUE THREAD

**Issue by adrianpetcu** [ah-/rdkafka-dotnet#103]
I have a scenario in which a message processor consumes the messages from a topic and should take some actions based on the previous message with the same key.  I would prefer to rely only on the Kafka data and not to store the previous message in a data store.

Is it possible to get all the messages that have a specific key?

**Comment by treziac** [comment]
No, all you can do is rely on the fact that data with the same key will end in the same partition and assign only this partition (but be aware that this may not be true after rebalancing / cluster modification / broker failure).
Depending on you scenario, you may also look at kafka stream or other stream processing service which may fit your needs, but it's unrelated with rdkafka (and may be overkill given your usage) Under the hood, it just do what you said, keep the keys in memory :)

**Comment by adrianpetcu** [comment]
Thanks, @treziac! My scenario is simple and I'll go with a small dev, adding a stream processing service would be too much.
