### ISSUE TITLE
detect earliest+last available offset on a per partition basis for a topic?

### ISSUE THREAD

**Issue by bkim54** [ah-/rdkafka-dotnet#109]
is this possible? or something like this method (https://kafka.apache.org/0101/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html#position(org.apache.kafka.common.TopicPartition)
where I can query the next offset that will be fetched?

**Comment by tomasdeml** [comment]
Maybe you want [Consumer.GetWatermarkOffsets](https://github.com/ah-/rdkafka-dotnet/blob/master/src/RdKafka/Consumer.cs#L152) method?

**Comment by bkim54** [comment]
thanks I didnt realize that method existed! i used [Handle.QueryWatermarkOffsets](https://github.com/ah-/rdkafka-dotnet/blob/master/src/RdKafka/Handle.cs#L140) instead
