### ISSUE TITLE
LibRdKafka static constructor throwing

### ISSUE THREAD

**Issue by edwinloubser** [ah-/rdkafka-dotnet#11]
I get the following error when trying to use the library: "The type initializer for 'RdKafka.Internal.LibRdKafka' threw an exception." I can see the librdkafka.dll & zlib.dll files exists in the x64 & x86 folders in the bin directory.

The project I'm using to test is a regular .451 console project and I just added rdkafka-dotnet via nuget.

Any suggestions?

**Comment by ah-** [comment]
Could you upload a complete example somewhere? Then I'll have a closer look tonight.

Does it say anything more about what failed?

**Comment by edwinloubser** [comment]
Sure I have put in on dropbox: https://www.dropbox.com/s/93fp8aug2q99ay8/RdKafkaTester.zip?dl=0

There is no detail in the exception. So I can't give any more information unfortunately.

**Comment by ah-** [comment]
It loads fine on my machine, without any modifications. This makes me suspect you're missing some dependency of the bundled librdkafka.dll, could you please check with http://www.dependencywalker.com/depends22_x64.zip?
It might be the vc140 runtime or the OpenSSL libraries, if it's the latter try installing http://slproweb.com/products/Win32OpenSSL.html
I might have to bundle those up better.

Also your tester will run much faster if you send messages in batches/don't await every single message individually. librdkafka tries to batch messages for you and then waits for the broker to write the message to disk, which means there might be some latency.

**Comment by edwinloubser** [comment]
Thanks you for doing the investigation, turns out it was the OpenSSL libraries. Yes I would suggest to find a way to bundle the OpenSSL libraries in the NuGet package. Also I would suggest indicating that the vc140 runtime is required, it is something that would need to be installed on a server.

As per your suggestion of batching the messages, that is one of the things I was trying to figure out. How is this achieved, there does not seem to be a method that takes a list of messages?

As a side note, we have our own Kafka library (closed source) and I'm trying to ascertain if c++ one is good enough performance wise for us to use, hence the benchmarking code. I designed our producer to internally do batches and buffering, based on time and batch size. It is very useful because it lowers the barrier to entry considerably, it might be worthwhile to do the same for this library.

**Comment by ah-** [comment]
I'll have a look at somehow bundling Openssl, I hope there's a way without having to ship my own copy.

About the batching, librdkafka does pretty much what you describe, it accumulates messages before sending them out. It actually also exposes the batch interface you mention, see https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h rd_kafka_produce_batch. Exposing that wouldn't be too hard.

**Comment by edwinloubser** [comment]
Good to know that it is supported by rdkafka. I think it does make sense to expose the batching interface. Until then how would I do this? Currently the Produce method only seem to accept a single message payload.

A more general question which I hope you can answer is, what happens when brokers go down or there are network partitions. Does rdkafka handle this internally? Or is it up to the consumer of the library to handle this?

**Comment by ah-** [comment]
Just call produce multiple times without waiting for the previous one to complete. It will batch it up for you internally. See the examples, they register continuations instead of awaiting.

Librdkafka handles brokers going down, on network failures it will keep trying for a configurable time and only error if that timeout expires.

**Comment by edwinloubser** [comment]
Is it fine to ignore the task returned, as don't really care about the return value? If the produce method call is not being awaited, what stops consuming code to overrun the producer? It seems by not awaiting or some form of blocking it is allowing unbounded memory growth?

**Comment by ah-** [comment]
Should be fine, librdkafka has an internal send queue which is limited in size, I think it's 1gb by default. Once that's full, it will return an error to indicate that, and currently the C# wrapper handles that by waiting for a short while and then retrying.

On windows this seems to not quite happen though at the moment, see https://github.com/edenhill/librdkafka/issues/571

Also have a read through https://github.com/edenhill/librdkafka/blob/master/INTRODUCTION.md and https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

**Comment by edwinloubser** [comment]
Yes I can confirm I'm running into the issue raised in edenhill/librdkafka#571  Hopefully it will get resolved soon. Thank you I had a look at the documentation and configuration.

**Comment by ah-** [comment]
Give RdKafka.0.9.1-ci-76 a spin, fixed the send issue now.

I'm getting these numbers with your example when sending 2 million messages:
Total:
Duration:        34233 ms
Ops / sec:       58 422
Transfered:      1,953.12 Mb
Mb / second:     57.05

**Comment by StephenDrewLDS** [comment]
I am also getting this.

Whenever I try and start a project with rdkafka.net, I get the following popup:

"The program can't start because LIBEAY32.dll is missing from your computer.  Try reinstalling the program to fix this problem".

I will install OpenSSL now and cross my fingers :)

**Comment by ah-** [comment]
Noted, I'm currently on holiday and will have a look once I'm back home.

I'd like to find a solution where I don't have to bundle my own Openssl so I don't have to do a release every time Openssl fix a bug.

**Comment by StephenDrewLDS** [comment]
Cool.  Have a nice holiday!

**Comment by ah-** [comment]
After looking at how other projects handle this (in particular grpc) I think the way to go is to statically link zlib and OpenSSL on Windows. I suspect switching to BoringSSL would be worth it as well.

**Comment by ah-** [comment]
Give RdKafka.0.9.1-ci-79 a try, now links OpenSSL statically so you won't need the dll. Feel free to reopen if you still have issues.

**Comment by namroot** [comment]
I have the same message of error. A same problem with LibRdKafka "The type initializer for 'Confluent.Kafka.Impl.LibRdKafka' threw an exception".
In my local machine, the application works correctly. But when i try to deploy it in the server, i have this error.
I am in dot.net environment (c#) and i am using Confluent.Kafka.0.9.4-preview2 library.
Local machine:  Windows 7 Entreprise Service pack 1.
Server: Windows Server 2008 R2 Entreprise Service Pack 1.

Any suggestions please?

**Comment by namroot** [comment]
I tried  to install OpenSSL but without result.
