### ISSUE TITLE
Usage guidelines

### ISSUE THREAD

**Issue by cpx86** [ah-/rdkafka-dotnet#110]
There isn't much in the documentation in terms of usage guidelines. More specifically, should Producer and/or Topic instances be re-used or should singleton instances be used? What is the cost of creating new instances of each? What happens when they are disposed?

**Comment by ah-** [comment]
They're relatively heavy-weight as they create threads to communicate with the different brokers. I'd recommend creating only few instances.

When you dispose them they're shut down and they need to do quite a bit of work again on construction.

**Comment by cpx86** [comment]
I suspected as much, but good to have verified :) Would be nice to have that info in the examples.
