### ISSUE TITLE
Assign a strong name to assembly

### ISSUE THREAD

**Issue by jdn1978** [ah-/rdkafka-dotnet#114]
I'm attempting to incorporate this library into an SSIS package to use for a custom Kafka data source.  My final roadblock is that the DLL by default has no strong name or signature assigned.  This is causing execution to fail in SSIS.  It appears fixing it will require compiling the source with an assigned key, which I believe is allowable under the licensing.  Has anyone else encountered this (or a similar issue), and if so how did you resolve it?

**Comment by ah-** [comment]
Would you mind asking at https://github.com/confluentinc/confluent-kafka-dotnet? Confluent are now maintaining this client.
