### ISSUE TITLE
rdkafka-dotnet updates needed for Apache Kafka 0.10.1.1

### ISSUE THREAD

**Issue by josetzamora** [ah-/rdkafka-dotnet#115]

**Comment by josetzamora** [comment]
It appears that librdkafka isn't ready yet.

> The API version query is currently disabled by default (api.version.request=false) in librdkafka (as of May 2016) due to the afforementioned bug in broker version 0.9.0.0 & 0.9.0.1.
> 
> NOTE: As more users move to broker version >= 0.10.0.0 the default value of api.version.request will be changed to true in librdkafka. Please read future release notes to know when this happens since it will affect users of <0.10.0 brokers.

**Comment by treziac** [comment]
rdkafka-dotnet should work with kafka 0.10.1.1 (it might not necessarily use the latest broker feature, but brokers can deal with previous client implementation - I'm using brokers on 0.10.1.0 without problem)

You can set api.version.request=true if you use the prerelease build (which point to librdkafka 0.9.2 which  introduced this feature)

**Comment by ah-** [comment]
As treziac said, I believe it already supports 0.10.x.
