### ISSUE TITLE
Update to librdkafka 0.9.3 and add ability to produce message timestamp

### ISSUE THREAD

**Issue by BDeus** [ah-/rdkafka-dotnet#116]
The librdkafka add the ability to produce message timestamp now.
https://github.com/edenhill/librdkafka/commit/15d3e7ea8589fcf0a81f5631e9d74f88630fa7bf

Is it be planned to add this feature in rdkafka-dotnet?

**Comment by ah-** [comment]
Have a look at https://github.com/confluentinc/confluent-kafka-dotnet, this client is now developed by Confluent and they have already added timestamp support.
