### ISSUE TITLE
Errors Consuming Local Data

### ISSUE THREAD

**Issue by bryanjeffrey** [ah-/rdkafka-dotnet#117]
Hello.

I was working to move over from RdKafkaNet (https://github.com/ah-/rdkafka-dotnet).  I converted our codebase over to using the confluent library.  However, running a simple test console application I am seeing the following error when subscribing to topics:

5|2017-02-21 09:25:22.482|rdkafka#consumer-1|FAIL| localhost:9092/12: Connection closed

The Kafka console consumer is working against the same Kafka server/Zookeeper (a single node local instance I am using for test), so that would not seem to be the issue.  On the Kafka Server side I am seeing the following errors:

[2017-02-21 09:36:34,509] ERROR Closing socket for /127.0.0.1 because of error (kafka.network.Processor)
org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'topics': java.nio.BufferUnderflowException
        at org.apache.kafka.common.protocol.types.Schema.read(Schema.java:66)
        at org.apache.kafka.common.requests.JoinGroupRequest.parse(JoinGroupRequest.java:85)
        at kafka.api.JoinGroupRequestAndHeader$.readFrom(JoinGroupRequestAndHeader.scala:29)
        at kafka.api.RequestKeys$$anonfun$12.apply(RequestKeys.scala:50)
        at kafka.api.RequestKeys$$anonfun$12.apply(RequestKeys.scala:50)
        at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
        at kafka.network.Processor.read(SocketServer.scala:450)
        at kafka.network.Processor.run(SocketServer.scala:340)
        at java.lang.Thread.run(Thread.java:745)

I've verified that the list of topics going into consumer.subscribe is correct (it's a list of one - "test").  Could this be a Kafka version issue?  My local version is (2.10) 0.8.2.1

**Comment by bryanjeffrey** [comment]
Just tried Kafka 0.9.0.1 and this error is no longer seen.

**Comment by bryanjeffrey** [comment]
While I'm no longer seeing an error after the Kafka version change, I am not seeing consumed messages.  I've worked all the way back from my code back to the example code for both poll and consume advanced consumer (https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/examples/AdvancedConsumer/Program.cs).  Neither of these samples appear to work out of the box.  

The older RdKafka code continues to work, and I also see the Kafka console consumer/producer produce/consume data.  I've tried the following:
1. Turned on exception processing - no exceptions to note.
2. Verified connection to the broker from broker logs & validated exception when broker is terminated
3. Double checked correct topic specification

Do you have any thoughts on how I could further debug this issue?

Thank you!

**Comment by treziac** [comment]
Wasn't this supposed to be post in https://github.com/confluentinc/confluent-kafka-dotnet instead? (you point to their example)

In any case, do you receive an OnPartitionAssigned? 

You can enable debug by setting the "debug" config to "cgrp,topic,fetch"
(see librdkafka for more info on this)

**Comment by bryanjeffrey** [comment]
@treziac  - Yes, I did mean to post this to confluent.  The library here works OK, but their library does not.  I do not receive an OnPartitionAssigned event.  I suspect the need to specify Kafka version is the issue.

 I will close the issue here - thank you for the tip on debugging.
