### ISSUE TITLE
LibRdKafka static constructor throwing

### ISSUE THREAD

**Issue by namroot** [ah-/rdkafka-dotnet#119]
I have the same message of error. A same problem with LibRdKafka "The type initializer for 'Confluent.Kafka.Impl.LibRdKafka' threw an exception".
In my local machine, the application works correctly. But when i try to deploy it in the server, i have this error.
I am in dot.net environment (c#) and i am using Confluent.Kafka.0.9.4-preview2 library.
Local machine: Windows 7 Entreprise Service pack 1.
Server: Windows Server 2008 R2 Entreprise Service Pack 1.
I tried  to install OpenSSL but without result.
Any suggestions please?

**Comment by edenhill** [comment]
Please file an issue on https://github.com/confluentinc/confluent-kafka-dotnet and close this one.
