### ISSUE TITLE
Where can I find the pdb file of librdkafka.dll

### ISSUE THREAD

**Issue by k0ngk0ng** [ah-/rdkafka-dotnet#121]
hi, @ah- 
I have some problems in my project by using rdkafka.
A exception was thrown by librdkafka which is from the package RdKafka.Internal.librdkafka.0.9.1.
I am now debugging with the dump files, but i haven't got the pdb of librdkafka.
So I cannot find why the program crashed.
Can you provide the pdb file?

**Comment by ah-** [comment]
Hi,

see https://github.com/ah-/librdkafka-build and https://ci.appveyor.com/project/ah-/librdkafka-build for the build scripts and the CI server.

I'm not sure if it archives the pdb though.
