### ISSUE TITLE
Expose librdkafka 0.9.4

### ISSUE THREAD

**Issue by MaximGurschi** [ah-/rdkafka-dotnet#122]
Since it is not trivial to update our code to use the Confluent driver within the necessary timeline, can you consider releasing an updated package for librdkafka - 0.9.4? That includes some bug fixes that we currently encounter.

**Comment by treziac** [comment]
@MaximGurschi 
You can simply replace the librdkafka.dll in your bin folder at deployment, this will work :)

If you don't want to make custom deployment task and are working with the new nuget project reference, you could also:
- Add a reference to RdKafka.Internal.Librdkafka, and specify you don't want to include any assets (`<ExcludeAssets>all</ExcludeAssets>`)
- Add a reference to librkafka.redist 0.9.4

What is the non trivial part for migrating to Confluent.Kafka? You will want to eventually migrate it as Andreas stated the project moved

**Comment by MaximGurschi** [comment]
Thanks treziac. Tried that but to get it to work i:

- Added a reference to librkafka.redist 0.9.4
- deleted line (<Import Project="$(SolutionDir)packages\RdKafka.Internal.librdkafka*) from the csproj file. 

My API is a wrapper around RdKafka and looking at the confluent API i stopped when i realised that producer topic management is now different. Will have to set aside time to change the way i interact with the .net driver if/when we switch to the new client.
