### ISSUE TITLE
is creating a consumer create another thread?

### ISSUE THREAD

**Issue by bkim54** [ah-/rdkafka-dotnet#123]
whenever I create a new consumer or eventconsumer, is that consumer (and the onMessage callbacks) live in a new thread or in thread that created it?

Thanks!

**Comment by ah-** [comment]
In a new thread. It starts it via Task.Factory.StartNew(..., TaskCreationOptions.LongRunning, TaskScheduler.Default);.

**Comment by bkim54** [comment]
thanks!
