### ISSUE TITLE
what is the log.message.format.version?

### ISSUE THREAD

**Issue by bkim54** [ah-/rdkafka-dotnet#126]
if I use rdkafka will my consumers be able to read log.message.format 0.10.0 and greater, without the broker having to do message conversion?

**Comment by edenhill** [comment]
@bkim54 Yes, given that you configure "api.version.request": true in your client.

**Comment by bkim54** [comment]
thanks @edenhill! is there a way to get the timestamp out of the received message? it does not seem to be a field within the [`RdKafka.Message`](https://github.com/ah-/rdkafka-dotnet/blob/master/src/RdKafka/Message.cs) struct

**Comment by edenhill** [comment]
Yes, but you should be looking at the successor to RdKafka-dotnet: 
https://github.com/confluentinc/confluent-kafka-dotnet

It exposes Message.Timestamp

**Comment by bkim54** [comment]
ah yes we are planning on moving to confluent's client but they do not yet support custom partitioners which is a must have for us so we are waiting for that functionality before migrating
