### ISSUE TITLE
No such host is known.

### ISSUE THREAD

**Issue by cysnet** [ah-/rdkafka-dotnet#132]
the below code 
`DeliveryReport deliveryReport = await topic.Produce(data);`
can not run correctly,and the error message is :
3|2019-01-09 18:24:46.764|rdkafka#producer-1|FAIL| iz2zei2y693gtrgwlibzlwz:9092/0: Failed to resolve 'iz2zei2y693gtrgwlibzlwz:9092': No such host is known.

**Comment by ah-** [comment]
Hi,

iz2zei2y693gtrgwlibzlwz does look like an unusual host name, are you sure that's correct? It might just need the correct host name for the broker in the config.

Also I'd recommend switching to https://github.com/confluentinc/confluent-kafka-dotnet, which is a much improved and actively maintained version of this client.

**Comment by cysnet** [comment]
> Hi,
> 
> iz2zei2y693gtrgwlibzlwz does look like an unusual host name, are you sure that's correct? It might just need the correct host name for the broker in the config.
> 
> Also I'd recommend switching to https://github.com/confluentinc/confluent-kafka-dotnet, which is a much improved and actively maintained version of this client.

i have resolved this problem ,the reason for this problem is because the configuration item in kafka's configuration file: "advertised.listeners" is not set correctly.thank you anyway
