### ISSUE TITLE
Q: What version of librdkafka is currently bundled?

### ISSUE THREAD

**Issue by tomasdeml** [ah-/rdkafka-dotnet#16]
Hi,
first off, thank you for this very fine library! :)

I'm using `v0.9.1-ci-79` from NuGet and seem to be hitting [this issue](https://github.com/edenhill/librdkafka/issues/382). Is there any way how to find out whether this bug is fixed in the version of `librdkafka` that is currently bundled with `rdkafka-dotnet`?

Best regards,
Tomas Deml.

**Comment by ah-** [comment]
Cool, happy to hear you like it!

rdkafka-dotnet is published by a job on appveyor, starting from `v0.9.1-ci-79` you can look that build up on https://ci.appveyor.com/project/ah-/rdkafka-dotnet/history. Looking at  https://ci.appveyor.com/project/ah-/rdkafka-dotnet/build/1.0.79 shows you it's current master.

Current master pulls in librdkafka via https://github.com/ah-/rdkafka-dotnet/blob/master/src/RdKafka/project.json, which uses RdKafka.Internal.librdkafka-Windows 0.9.1-ci-26. That also gets built via CI, the corresponding build is here: https://ci.appveyor.com/project/ah-/librdkafka-build/build/0.9.1-ci-26

In the librdkafka build log you'll find the submodule commit "a7424f8 Ignore GroupCoordinatorResponsne ERR_GROUP_COORDINATOR_NOT_AVAILABLE": https://github.com/edenhill/librdkafka/commit/a7424f8a249b9f0866c34c95b5c6f9c8d67d5d30
