### ISSUE TITLE
BUG: Negative delivery report breaks delivery report callback

### ISSUE THREAD

**Issue by tomasdeml** [ah-/rdkafka-dotnet#17]
When a negative delivery report for a previously produced message is received, e.g. `_MSG_TIMED_OUT`, a bug in the delivery callback (`Producer.DeliveryReportCallback`) triggers an unhandled exception. The exception is propagated to `librdkafka` which then stops working - no further delivery report callbacks will be invoked during `rd_kafka_poll`. From this point on, no async `Task`s for pending or newly produced messages will complete nor fail. This effectively causes a memory leak when new messages are produced.

Steps to reproduce:
1. Produce some messages in an endless loop
2. Take down Kafka broker for the partition
3. Wait for `message.timeout.ms` so that some messages time-out
4. Restart the broker
5. Send new messages

**Comment by ah-** [comment]
Great sleuthing, thanks a lot for digging down and fixing this!
