### ISSUE TITLE
Build nuget packages

### ISSUE THREAD

**Issue by ah-** [ah-/rdkafka-dotnet#2]
Build nuget packages for rdkafka, ideally including pre-built librdkafka.dlls for win32/64, to make it easy to use.

**Comment by edenhill** [comment]
Optimally there should be NuGet librdkafka packages though, right?

**Comment by ah-** [comment]
Ideally yes, having packages for that would help a lot.
There might be a little bit of build magic required to get downstream programs to include the librdkafka dlls properly in their output though.

**Comment by ah-** [comment]
Done: https://www.nuget.org/packages/RdKafka
