### ISSUE TITLE
Consumer examples

### ISSUE THREAD

**Issue by avoxm** [ah-/rdkafka-dotnet#20]
The most common scenarios for consumers are either to fetch from the "beginning" or fetch from where it was left off. 

It would be really helpful to have examples for these scenarios.

**Comment by avoxm** [comment]
At the moment it looks like that consumer reads the data from the end only even if I set the offset manually.

**Comment by ah-** [comment]
I agree, there's now an FAQ wiki page here: https://github.com/ah-/rdkafka-dotnet/wiki/Faq
Feel free to extend with things that you found most puzzling.

How do you think this documentation should best be done? I like runnable code, so I've put a lot into the AdvancedConsumer/Producer examples, librdkafka has so many features that it would take a whole lot of example projects to cover everything.

**Comment by avoxm** [comment]
@ah- thanks, will look into it and close this ticket.

**Comment by ah-** [comment]
Cool, let me know if you have a good idea and feel free to contribute examples!
