### ISSUE TITLE
GetOffsets throws an exception 

### ISSUE THREAD

**Issue by avoxm** [ah-/rdkafka-dotnet#21]
Calling GetOffsets throws the below exception.

Code : `var offsets = await consumer.GetOffsets(topicName, 1);`

> 
> An exception of type 'System.EntryPointNotFoundException' occurred in RdKafka.dll but was not handled in user code
> 
> Additional information: Unable to find an entry point named 'rd_kafka_get_offsets' in DLL 'librdkafka'.

**Comment by ah-** [comment]
Thanks, will have a look tonight.

**Comment by ah-** [comment]
Fixed now, the function got renamed upstream.
