### ISSUE TITLE
How to consume earliest/latest offset?

### ISSUE THREAD

**Issue by MaximGurschi** [ah-/rdkafka-dotnet#22]
Given an EventConsumer, what is the proper way to start consuming from:
a.First possible offset from all partitions
b.Last possible offset from all partitions

I looked into the underlying C library and thought that the above is achievable via doing:
_consumer.Subscribe(new List<string> { ... });_
a.consumer.Assign(new List<TopicPartitionOffset>() {new TopicPartitionOffset(topicName,0, **-2**) });
b.consumer.Assign(new List<TopicPartitionOffset>() {new TopicPartitionOffset(topicName,0,**-1**) });

, but that does not look like it works. I got the magic values from rdkafka.h:
#define RD_KAFKA_OFFSET_BEGINNING -2  //< Start consuming from beginning of kafka partition queue: oldest msg
#define RD_KAFKA_OFFSET_END       -1  //< Start consuming from end of kafka partition queue: next msg

Can you please tell me what the correct way to do a and b is? Should I use consumer.Asign zero/long.MaxValue?

**Comment by ah-** [comment]
You almost got it, the trick is that the .Assign with the custom offset has to happen within the OnPartitionsAssigned event.

Try this:
```csharp
consumer.OnPartitionsAssigned += (obj, partitions) => {
    Console.WriteLine($"Assigned partitions: [{string.Join(", ", partitions)}], member id: {consumer.MemberId}");
    var fromBeginning = partitions.Select(p => new TopicPartitionOffset(p.Topic, p.Partition, Offset.Beginning)).ToList();
    Console.WriteLine($"Updated assignment: [{string.Join(", ", fromBeginning)}]");
    consumer.Assign(fromBeginning);
};
```

There are now constants for the magic values, and I'm very much considering just making offset numbers strongly typed with their own struct that then also prints those magic numbers properly.

I've started an FAQ wiki page here: https://github.com/ah-/rdkafka-dotnet/wiki/Faq so it's documented somewhere. Please feel free to update and extend!

**Comment by MaximGurschi** [comment]
This is great and very quick of you! Thank very much. It works as "advertised" :)

**Comment by MaximGurschi** [comment]
Sorry for reopening this. Is it possible to rewind an existing consumer? So i can set the offset at instantiation when OnPartitionAssigned triggers. But how do i make the assignment after? Do i need to create a new consumer? Would be great if you can do it with the existing instance.

**Comment by ah-** [comment]
Yes, just modify the consumers assignment:

```cs
var reset = consumer.Assignment.Select(p => new TopicPartitionOffset(p.Topic, p.Partition, Offset.Beginning)).ToList();
consumer.Assign(reset);
```

Does this work for you? There's a couple of alternative ways but this is the most straightforward.

**Comment by MaximGurschi** [comment]
Interestingly that was what i tried and thought it did not work. But indeed you are correct it works, i just had to wait longer :). Thanks! Case closed again!

**Comment by bkim54** [comment]
@ah- you said assign must be called within onPartitionsAssigned, but I set it before calling consumer.Consume(). in your example SimpleConsumer you also call Assign before
```
consumer.Assign(new List<TopicPartitionOffset> {new TopicPartitionOffset(topics.First(), 0, 5)});
consumer.Start();
```
what is the correct way?
