### ISSUE TITLE
BUG: Garbled payload in delivery report when in-flight message times out

### ISSUE THREAD

**Issue by tomasdeml** [ah-/rdkafka-dotnet#26]
Hi,
I'm hitting a bug either in _rdkafka-dotnet_ or (more likely) in _librdkafka_ itself. When an in-flight message times out (e.g. when the message is huge and the message timeout is set too low), the `Producer.DeliveryReportCallback` receives a `rd_kafka_message` with garbled error string in the `payload` field:

> RdKafka.RdKafkaException: ^è7Z/Vâ╪?o_-,U$<Lí(_ª{‼è#X>OYÿ→D!¬"→-◄Y`s;ECn (Error _MSG_TIMED_OUT - Local: Message timed out)

I can consistently reproduce the issue by sending 100 messages with 20 MB payload when the `message.timeout.ms` is set to `5000`. However it can be also easily reproduced with relatively small messages (e.g. 500 kB) and very low message timeout (e.g. `5` ms). 

You can find a repro case along with the garbled output in [this gist](https://gist.github.com/tomasdeml/ebc8152d36990cb10bb754e7830cc6e4).

The application does not crash so it is not critical. However it may indicate some deeper issue.

**Comment by ah-** [comment]
Thanks, will have a look tonight.

**Comment by edenhill** [comment]
So I think this stems from bad message_t documentation regarding payload/error string.

message_t.payload is always the original payload in the producer case (dr_cb), regardless of .err.
It is only in the consumer where the payload doubles as detailed error string in case of .err != 0.

The documentation will be updated soon.

**Comment by ah-** [comment]
That was it, fixed now.
