### ISSUE TITLE
Consumer to receive messages for new topic

### ISSUE THREAD

**Issue by MaximGurschi** [ah-/rdkafka-dotnet#27]
Hello. If a consumer starts before a topic is created then it will never receive any messages. My scenario is:

1.Topic X does not exist
2.Consumer starts
3.Producer starts some time later and creates X

Consumer's log indicates that eventually the returned metadata includes the name of the new topic X. My guess is that OnPartitionsAssigned should trigger and make a new assignment.

So far i tried reducing "topic.metadata.refresh.interval.ms" this did not help. Setting "auto.offset.reset" in the Consumer's config throws. Is this expected?

What is the correct way for the consumer to start receiving messages? On a related note, is there any reason the consumer has to retrieve the whole list of topics? It is a consideration in case the list is large and the consumer needs to retrieve all that data for no reason.

**Comment by ah-** [comment]
I think that' one for upstream librdkafka.

**Comment by MaximGurschi** [comment]
Thanks you for the speedy reply. I have forwarded on the question.
