### ISSUE TITLE
Does the client need to query the broker for the whole list of topics?

### ISSUE THREAD

**Issue by MaximGurschi** [ah-/rdkafka-dotnet#28]
Hello,

Is there any reason the consumer has to retrieve the whole list of topics? It is a consideration in case the list is large and the consumer needs to retrieve all that data for no reason.

There was a somewhat related question at librdkafka: [https://github.com/edenhill/librdkafka/issues/648](url)

Basically i want to do the same, check if the cluster is "up". Can i do that without retrieving the whole list of topics and without doing "Producer.Topic" for some dummy topic name?

**Comment by edenhill** [comment]
The Metadata request to retrieve the cluster topics and brokers is currently a bit limited for this use case:
You either request all topics to be returned, or you request one or more specific topics.
The latter form will create those topics if they dont exist and auto.create.topics.enable=true, which is most likely not what you want. On the other hand, if you know there is a topic that will always exist in your cluster you can query that.

There is some work around this in KIP-4, but that is past the 0.10.0.0 release.

**Comment by MaximGurschi** [comment]
Thank you for that. (I am using auto.create.topics.enable=true) I thought the topic will only be created for a produce call and not a query metadata call. I will keep an eye out for v > 0.10.0.0.
