### ISSUE TITLE
Is consumer.Position safe to call if the cluster is not "up"

### ISSUE THREAD

**Issue by MaximGurschi** [ah-/rdkafka-dotnet#31]
Hello,

I ended up implementing dynamic (entire) cluster fail-over for both the producer and consumer. The logic is wrapped in an API i'm developing. 

Assume the scenario:
1.Consumer C
2.Topic T
3.C consumes from DC1 (cluster in data centre 1)
4.DC1 is offline
5.C dynamically fails over to DC2

At step 5 i want to provide the consumer with information for T:
1.QueryWatermarkOffsets (consumer.QueryWatermarkOffsets)
2.Committed (consumer.Committed)
3.Position (consumer.Position)

Ideally i would provide the 3 values for both DC1 and DC2. The idea is that C can use some heuristic to decide where to consume from when failed over from DC1 to DC2.

I believe that I cannot get values 1, 2 for DC1 as it is offline and those are round trip queries. Can i instead safely retrieve value 3? Or should i keep track of the consumed message offset myself?

**Comment by ah-** [comment]
Yes, Position just reads a local offsets, no roundtrip involved. There's also rd_kafka_get_watermark_offsets (https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L1525) which returns the last known watermark without a broker query, but I'm not sure if that's exposed in C# yet.

**Comment by MaximGurschi** [comment]
I appreciate the feedback - that makes sense. Is it possible for you to expose that method in the .net client? It will help with getting the last known high watermark, the low can be cached once when i (re)establish the connection (as i am not enabling stats this is the best effort i can make for low watermark).

As for the last committed offset - i realise i can do a best effort and keep track of that in the OnOffsetCommit.

**Comment by ah-** [comment]
Added, try this once Appveyor has uploaded the package:

```csharp
var offsets = consumer.GetWatermarkOffsets(new TopicPartition("test", 0));
Console.WriteLine($"HWM: {offsets.Low} {offsets.High}");
```

**Comment by MaximGurschi** [comment]
Works nicely, thank you!
