### ISSUE TITLE
Offset lagging by 1 when using Commit(msg)

### ISSUE THREAD

**Issue by lassebv** [ah-/rdkafka-dotnet#32]
Hi,

I am using Kafka in a classic message broker scenario where I want fine grained control of each message consumed. I am therefore using manual commit. My issue is now that when I use Consumer.Commit(msg) it seems that the offset is lagging 1 behind the consumed messages (verified by using the command line tool kafka.admin.ConsumerGroupCommand). This problem disappears if I use Consumer.Commit() without specifying a message or alternatively a list of TopicPartitionOffset's where I manually increment the offset by 1 relative to the offset given in the mssage. It seems to me that perhaps the offsets given to Commit should be incremented by one before being parsed to librdkafka. 

I am new to Kafka, so I am unsure if this is indeed an error with the library, or if it is simply me who have misunderstood some best practices.

Best Regards
Lasse

**Comment by ah-** [comment]
That sounds like a bug, will fix this tonight.

**Comment by lassebv** [comment]
Awesome!

**Comment by ah-** [comment]
Fixed, thanks a lot for reporting this!
