### ISSUE TITLE
'System.TypeInitializationException' occurred in RdKafka.dll

### ISSUE THREAD

**Issue by devsschmidt** [ah-/rdkafka-dotnet#34]
Hi,

when i try to implement a consumer like the example mentionened in readme section the following 
line

`var config = new Config() { GroupId = "example-csharp-consumer" };`

causes this exception
    System.TypeInitializationException was unhandled
      HResult=-2146233036
      Message=Der Typeninitialisierer für "RdKafka.Internal.LibRdKafka" hat eine Ausnahme verursacht.
      Source=RdKafka
      TypeName=RdKafka.Internal.LibRdKafka
      StackTrace:
           bei RdKafka.Internal.LibRdKafka.conf_new()
           bei RdKafka.Internal.SafeConfigHandle.Create()
           bei RdKafka.Config..ctor()
           bei kafka_consumer_example.Program.Main(String[] args) in C:\Users\stc\Development\git\kafka-consumer-example\Program.cs:Zeile 18.
           bei System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
           bei System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
           bei Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
           bei System.Threading.ThreadHelper.ThreadStart_Context(Object state)
           bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
           bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
           bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
           bei System.Threading.ThreadHelper.ThreadStart()
      InnerException: 
           HResult=-2146233052
           Message=Die DLL "librdkafka": Das angegebene Modul wurde nicht gefunden. (Ausnahme von HRESULT: 0x8007007E) kann nicht geladen werden.
           Source=RdKafka
           TypeName=""
           StackTrace:
                bei RdKafka.Internal.LibRdKafka.NativeMethods.rd_kafka_version()
                bei RdKafka.Internal.LibRdKafka.version()
                bei RdKafka.Internal.LibRdKafka..cctor()
           InnerException: 
    

the stacktrace looks like 

   in RdKafka.Internal.LibRdKafka.NativeMethods.rd_kafka_version()
   in RdKafka.Internal.LibRdKafka.version()
   in RdKafka.Internal.LibRdKafka..cctor()

i integrated the library via Nuget from https://www.nuget.org/packages/RdKafka/0.9.1-ci-131

can anyone tell me which assemblie i'm missing ?

the producer works fine.

**Comment by devsschmidt** [comment]
solved the issue with post build event as suggested here

http://stackoverflow.com/questions/37482895/system-typeinitializationexception-occurred-in-rdkafka-dll

**Comment by yasirk1** [comment]
@devsschmidt I'm not able to solve the exact same problem. I'm in Win10 and on an x64 environment. Can you share details of what exactly you copied where?

**Comment by devsschmidt** [comment]
@yasirk1, i installed RdKafka via NuGet like here 

https://www.nuget.org/packages/RdKafka/0.9.1-ci-131

then i went into my project settings (Visual Studio) and added the following lines into the After Build Events

```
copy /Y $(ProjectDir)packages\RdKafka.Internal.librdkafka.0.9.1-ci-16\runtimes\win7-x64\native\librdkafka.dll $(TargetDir)librdkafka.dll
copy /Y $(ProjectDir)packages\RdKafka.Internal.librdkafka.0.9.1-ci-16\runtimes\win7-x64\native\zlib.dll $(TargetDir)zlib.dll
```

**Comment by ah-** [comment]
Fixed now in RdKafka.0.9.1-ci-132 / RdKafka.Internal.librdkafka.0.9.1-ci-16.

There's a .props file in RdKafka.Internal.librdkafka (https://github.com/ah-/librdkafka-package/blob/master/src/RdKafka.Internal.librdkafka/build/RdKafka.Internal.librdkafka.props) which does the copying automatically but it stopped getting picked up due to a package name change.
