### ISSUE TITLE
Can LibRdKafka.LoadLibrary use the path of the currently executing assembly?

### ISSUE THREAD

**Issue by MaximGurschi** [ah-/rdkafka-dotnet#37]
Hello, I was wondering i this is something you would consider.
Running NUnit (without shadow copying), unless i force NUnit to use a different working dir, RdKafka fails to find the native dlls. This is because the following code uses relative paths.

Would you consider replacing this:

_LibRdKafka.LoadLibrary(flag ? "x64/zlib.dll" : "x86/zlib.dll");
LibRdKafka.LoadLibrary(flag ? "x64/librdkafka.dll" : "x86/librdkafka.dll");_

with this:
var baseDirectory = Path.GetDirectoryName(new Uri(Assembly.GetExecutingAssembly().GetName().CodeBase).LocalPath);
_LibRdKafka.LoadLibrary(**Path.Combine(baseDirectory**, flag ? "x64/zlib.dll" : "x86/zlib.dll"));
LibRdKafka.LoadLibrary(**Path.Combine(baseDirectory**, flag ? "x64/librdkafka.dll" : "x86/librdkafka.dll"));_

Note, this is not an RdKafka problem, but maybe the above is more appropriate anyway?

**Comment by ah-** [comment]
That's much better, could you test the latest CI build to confirm it works for you?

**Comment by MaximGurschi** [comment]
Yepp, works as expected. Thank you for the quick turnaround!

**Comment by ah-** [comment]
Cool, thanks for the patch!
