### ISSUE TITLE
Make RdKafka.Offset fields const

### ISSUE THREAD

**Issue by MaximGurschi** [ah-/rdkafka-dotnet#39]
I'm not sure if we are supposed to be allowed to overwrite fields:

    public static long Beginning = -2;
    public static long End = -1;
    public static long Stored = -1000;
    public static long Invalid = -1001;

, but it feels like they should be const.

**Comment by ah-** [comment]
Yes, agreed. Can you do a PR this time? Just fork the repo.

**Comment by MaximGurschi** [comment]
Thank you. Done.
