### ISSUE TITLE
Running on a Mac with Mono

### ISSUE THREAD

**Issue by yousifh** [ah-/rdkafka-dotnet#41]
After updating to RC2 tooling for dotnet, I wanted to try a sample app on a Mac with Mono using latest version of the library (0.9.1-ci-137). Running on .Net Core works fine. However when my sample app targets `net451` and trying to build against Mono 4.4, I kept getting common native library not found exception. 

I took a look at how Kestrel used to handle loading Libuv since I know that worked for me with RC2 using Mono. I noticed that they changed their native library loading for RC2 in this [commit](https://github.com/aspnet/KestrelHttpServer/commit/fe75aa47dbe4209600511543fb5b2f9aca055c8a). So I did the same thing and removed all the Mono specific native library loading that relied on `__Internal`  in RdKafka and tried again and it worked fine. I was able to publish messages and run my sample app using `dotnet run` or publishing it and doing `mono app.exe`. 

I can submit a PR with the change, but wanted to check if there are any problems with getting rid of that specific code or if you had other plans about loading librdkafka.

**Comment by ah-** [comment]
That sounds great, I think we can safely remove RC1 specific behaviour now.

If you put together a PR i'll merge it.
