### ISSUE TITLE
Cannot install for .net45

### ISSUE THREAD

**Issue by atharvai** [ah-/rdkafka-dotnet#43]
I receive the following error from Nuget:
`Could not install package 'RdKafka 0.9.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.` 

Please let me know how I can install this package for my project

**Comment by ah-** [comment]
Hi, could you upgrade to 4.5.1?

**Comment by ah-** [comment]
So to elaborate, .NET 4.5.0 has been officially deprecated for quite a while now: https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/

.NET 4.5.1 and up are supported, so all you need to do is to set that as the framework version.

**Comment by atharvai** [comment]
thanks! works!
