### ISSUE TITLE
Does disposing a Handle guarantee no more callbacks?

### ISSUE THREAD

**Issue by MaximGurschi** [ah-/rdkafka-dotnet#44]
Hello,

I looked at the RdKafka code and i believe that disposing a Handle (producer/(event)consumer) means that there will be no subsequent callbacks (OnError, OnPartitionsAssigned, LogCallbacks, etc.).
Can you please confirm if the above is correct and will stay like that?

I just want to make sure that I do not need to protect against subsequent callbacks after calling Dispose.

**Comment by ah-** [comment]
Yes. Callbacks only run in Tasks controlled by C# and those are shut down during Dispose.

See for example https://github.com/ah-/rdkafka-dotnet/blob/master/src/RdKafka/Handle.cs#L72.

**Comment by MaximGurschi** [comment]
Ok thank you for that.

**Comment by MaximGurschi** [comment]
To conclude - from Magnus:

_Logs may be emitted until rd_kafka_destroy() returns, but not after that.
The reason for this is that quite a lot of stuff might go on decommissioning librdkafka and thus logs are usable to find errors or for debugging._

That is good enough for me!

**Comment by ah-** [comment]
Thanks for investigating.

So the final answer is:
Yes, disposing a handle guaratees that no more callbacks are invoked after Dispose returns.
