### ISSUE TITLE
Producer Failed to create thread: No error

### ISSUE THREAD

**Issue by Nagendra82** [ah-/rdkafka-dotnet#45]
When i send the 1000 records  using this code.

public async void SendMessage(DataMessage msgdata, string  topicName,string KafkaUrl, TopicConfig topicConfig)
        {
 using (Producer producer = new Producer(config,KafkaUrl))
                using (Topic topic = producer.Topic(topicName, topicConfig))
                {
                    DeliveryReport deliveryReport = await topic.Produce(msgList.Serializer(), msgList.Select(x => x.FeedId).ToList().Serializer());
                 
                }
}

and i got this error 

Message: Failed to create thread: No error (0)
Details:    at RdKafka.Internal.SafeKafkaHandle.Create(RdKafkaType type, IntPtr config)
   at RdKafka.Handle.Init(RdKafkaType type, IntPtr config, LogCallback logger)
   at RdKafka.Producer..ctor(Config config, String brokerList)
   at PlasmaRdKafkaLib.PlasmaProducer.<SendMessage>d__6.MoveNext()

**Comment by ah-** [comment]
Are you maybe creating 1000 Producers?

You should create one and then reuse it. I suspect you're creating thousands of them which in the background creates thousands of threads, and at some point that starts failing.

So basically something like this:
```
class MyProducer : IDisposable
{
    private Producer _producer;
    private Topic _topic;

    public MyProducer(string kafkaUrl, ...)
    {
        _producer = new Producer(config, kafkaUrl);
        _topic = producer.Topic(topicName, topicConfig);
    }
    public Task<DeliveryReport> Send(key, message)
    {
        return topic.Produce(key, message);
    }
}
```

**Comment by Nagendra82** [comment]
Hi, 
Yes i have create 1000 of producer because i have read data from a consumer and sending to other topic (using producer) when new message is arrived.
Scenario is 
Producer  A send 1000 Message on topic T1 => Comsuner A reads T1 
Consumer A  read and process message and send to  => topic T2.

**Comment by ah-** [comment]
You can do that with just one producer, like this (in pseudocode):

```
var producer = new Producer();
var topic = producer.Topic(T2);
var consumer = new Consumer();

foreach (message in consumer.Subscribe(T1) {
     topic.Send(message);
}
```
