### ISSUE TITLE
How to Optimise the performance of rdKafka-dotnet

### ISSUE THREAD

**Issue by Nagendra82** [ah-/rdkafka-dotnet#46]
Hi Team,

I have a performance issue while reading the data from Consumer topic A and send the data using  Producer to topic B.
when i send 1000 of message on Consumer Topic A. its taking so much time.

Please find the code from below link
https://www.dropbox.com/s/kwetoh796oohaec/RdKafkaRestService.zip?dl=0

**Comment by ah-** [comment]
Looks like it still is creating a new producer for every send, which is hugely slow. Try this: https://gist.github.com/ah-/67af5db85b3b9ef5ca19968da22332c1


Also it's best to disable manual committing for now, so set EnableAutoCommit to true and remove this bit:
```csharp
                        if (!this.EnableAutoCommitOffset && msg.Offset % 10 == 0)
                        {
                            //  log.WriteTextLock("Committing offset");
                            consumer.Commit(msg).Wait();
                            //  log.WriteTextLock("Committed offset");
                        }
```

**Comment by ah-** [comment]
Oh, and it looks like the same is happening in kafkaService.svc.cs ProcessData, which does a `new PlasmaProducer` for every message.
You need to avoid creating a new Plasma/KafkaProducer for every message, or it will be slow. Just do the same thing as above, keep it in a variable

**Comment by Nagendra82** [comment]
Hi ,

I want read the data from consumer parallel but with my current code when i am sending 100 record it takes 4 second and with 200 records it takes 8 second.

please suggest me how can i process 4000 records in 1 second
Please find my code
[PlasmaProducer.txt](https://github.com/ah-/rdkafka-dotnet/files/346585/PlasmaProducer.txt)
[Consumer.txt](https://github.com/ah-/rdkafka-dotnet/files/346582/Consumer.txt)
[CallConsumer.txt](https://github.com/ah-/rdkafka-dotnet/files/346581/CallConsumer.txt)

**Comment by ah-** [comment]
Could you please do a quick test? Create a completely clean project without any of your existing code. Then add a single Producer for a single topic and send 100000 messages over it and measure how long that takes? Don't consume and produce, just have a loop that sends the same data over and over.

This should take 1-2 seconds, if it takes longer then something very basic is wrong.

I can't see anything obviously wrong with your example, but then I don't quite know what you're doing with it. Is your process even busy? Does the consumer run faster if you don't publish output messages? How many incoming messages do you have in the topic you read from?

**Comment by Nagendra82** [comment]
Hi, 
When i sending 10000 messages then it takes lot of time (aprox 3 minutes). i have created a sample for your reference please find the below link. 
https://www.dropbox.com/s/evasmd5zzjk41p9/LoadTesterForKafka.rar?dl=0

also find the kafka server configuration details. please suggest if some setting can improve the performance .
[Kafka Server Details.txt](https://github.com/ah-/rdkafka-dotnet/files/347198/Kafka.Server.Details.txt)

**Comment by Nagendra82** [comment]
Hi 
i am waiting your response.
