### ISSUE TITLE
MS Visual C++ Redistributable 

### ISSUE THREAD

**Issue by avoxm** [ah-/rdkafka-dotnet#48]
Is MS Visual  C++ 2015 redistributable a requirement ? 
Will MS Visual  C++ 2010 work ? 

I have a windows service that runs fine on a machine with C++ 2015 but fails on the one that has only C++ 2010. Could this be an issue ?

**Comment by ah-** [comment]
I think it currently needs the VS 2013 C++ redist.

It'd be nice to link librdkafka completely statically so this dependency goes away, it's just work that I don't quite have the time for right now.

See https://github.com/ah-/librdkafka-build and https://github.com/edenhill/librdkafka/tree/master/win32.
If you're interested enough in updating that build to link everything statically I'll gladly merge a PR and release a new RdKafka.

**Comment by avoxm** [comment]
Is there a way to make sure that it really needs at least MS C++ 2013 ?

**Comment by avoxm** [comment]
I have installed 
Visual C++ Redistributable Packages for Visual Studio 2013
and 
Visual C++ Redistributable Packages for Visual Studio 2015
it is still not working.

**Comment by ah-** [comment]
Could you check with http://www.dependencywalker.com/ that librdkafka.dll has all dependencies installed? Are there any other differences between the two servers?

**Comment by avoxm** [comment]
Thanks @ah- it turns out to be another issue, but Visual C++ Redistributable Packages for Visual Studio 2013 is required anyway.

**Comment by ah-** [comment]
Great. Did you get it to work in the end?

**Comment by avoxm** [comment]
Yes it is working now.
