### ISSUE TITLE
Failed to produce message (Error _BAD_MSG - Local: Bad message format)

### ISSUE THREAD

**Issue by aries-zhang** [ah-/rdkafka-dotnet#51]
Modified only kafka address & topic parameter in examples/SimpleProducer: 

```
public static void Main(string[] args)
{
    string brokerList = "10.177.201.87:9092";
    string topicName = "config-tag";

    using (Producer producer = new Producer(brokerList))
    using (Topic topic = producer.Topic(topicName))
    {
        Console.WriteLine($"{producer.Name} producing on {topic.Name}. q to exit.");

        string text;
        while ((text = Console.ReadLine()) != "q")
        {
            byte[] data = Encoding.UTF8.GetBytes(text);
            Task<DeliveryReport> deliveryReport = topic.Produce(data);
            var unused = deliveryReport.ContinueWith(task =>
            {
                Console.WriteLine($"Partition: {task.Result.Partition}, Offset: {task.Result.Offset}");
            });
        }
    }
}
```

Run the project, get the following exception:
```
{RdKafka.RdKafkaException: Failed to produce message (Error _BAD_MSG - Local: Bad message format)}
Failed to produce message (Error _BAD_MSG - Local: Bad message format)
```

- "10.177.201.87:9092" is a single node Kafka server created following [hello-samza](https://github.com/apache/samza-hello-samza) bootstrap instruction.
- "config-tag" is created on the Kafka server with the following command:   
```deploy/kafka/bin/kafka-topics.sh --zookeeper localhost:2181 --topic config-tag --replication-factor 1 --partition 1 --create```

**Comment by ah-** [comment]
What broker version are you running?

**Comment by aries-zhang** [comment]
Server: Ubuntu 16.04, Kafka 0.8.2.1
Client: Windows 10, RdKafka 0.9.1

**Comment by ah-** [comment]
Try setting the broker version explicitly:

```
var config = new Config();
config["broker.version.fallback"] = "0.8.2.1"
using (Producer producer = new Producer(config, brokerList))
```

See https://github.com/edenhill/librdkafka/wiki/Broker-version-compatibility

**Comment by aries-zhang** [comment]
Thanks a lot for the help , now it works fine 👍
