### ISSUE TITLE
How to assign producer configuration settings

### ISSUE THREAD

**Issue by toniralpatel** [ah-/rdkafka-dotnet#54]
@ah-  am trying to set below properties to producer, but getting **"No such configuration property: partition.assignment.strategy"** error message.

1. message.max.bytes
2. partition.assignment.strategy = "roundrobin"

Need quick help if someone already did this.
TIA!

**Comment by ah-** [comment]
Are you on the latest version? This looks good, partition.assignment.strategy should exist: https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md
