### ISSUE TITLE
Wildcard/regex support for consumer topic subscriptions?

### ISSUE THREAD

**Issue by erl7902** [ah-/rdkafka-dotnet#55]
Hi, I've been messing around with just setting up a basic consumer with this library and I noticed that librdkafka has regex support in the new high level consumers. I was wondering if this feature is present in rdkafka yet? Sorry if it is and I just missed it, I only tried a few basic things before figuring I should ask.

Thanks!

**Comment by edenhill** [comment]
Regex subscriptions are currently not supported on Windows due to lacking libc.
This will be sorted out for the coming release.

**Comment by erl7902** [comment]
Thanks, just wanted to double check,

**Comment by schaab** [comment]
@edenhill forgive my ignorance, does the lack of regex subscription support imply there is no wildcard support? So I can't do something like ` consumer.Subscribe(new List<string>{ "kafka.*" });`

**Comment by edenhill** [comment]
@schaab Correct, regexp/wildcard subscriptions are currently not supported on Windows.
On a side note the regexp wildcard must start with "^...." to be interpreted as a regexp.
