### ISSUE TITLE
EventConsumer Start after Stop

### ISSUE THREAD

**Issue by MaximGurschi** [ah-/rdkafka-dotnet#57]
Hello,

In brief i have an application that consumes from two clusters. **Dc1** and Dc2. At any point in time consumption is done from only one cluster. So I consume from **Dc1** and if If I detect that all brokers are down for **Dc1** then i failover to Dc2. Eventually if i detect that **Dc1** is available again then i failover back to **Dc1**. Both **DC1** and DC2 are 3-node clusters.

So here is the chain of method calls:
1.Subscribe to **Dc1**.
2.Call start on consumer to **Dc1**.
...
_I detect that i need to failover_:
3.Call EventConsumer.Stop on **Dc1** consumer.
4.Create connection to Dc2.
5.Subscribe to Dc2.
6.Call start on consumer to Dc2.
...
_I detect that **Dc1** is back again_:
7.Clean Dispose of connection to Dc2.
8.Subscribe to **Dc1**.
9.Call start on consumer to **Dc1**.
10.Consume from last (Kafka) committed offset.

After rebooting the servers of **Dc1**, i noticed that all the steps from 1-10 have completed. So far so good.
But then my application is not receiving any messages. At this point the topic (ABC) is at offset 150,000 and the consumer for **Dc1** is still at 120,000 and stays there. I can confirm that the internal polls of RdKafka are executing (so both of):
1.EventConsumer.consumerTask
2.Handle.callbackTask

, are running.

Unfortunately i did not enable complete logging for my application. But if i attach a debugger here is some of the internal linbrdkafka logs i see:
"rdkafka#consumer-5|7|BROKERFAIL|**Dc1**Machine2:9092/2: failed: err: Local: Broker transport failure: (errno: Unknown error)"
"rdkafka#consumer-5|7|OFFSET|Topic ABC [0]: setting offset INVALID for commit"
"rdkafka#consumer-5|7|BRKTP|**Dc1**Machine2:9092/2: Undelegating ABC [0]"
"rdkafka#consumer-5|7|OFFSET|Topic ABC [0]: setting offset INVALID for commit"

Do you have any ideas?

**Comment by MaximGurschi** [comment]
Are you supposed to call Subscribe+Start if you have previously called Stop? The way my application is written i guarantee that i do not call Dispose if i failover from **Dc1**, i only dispose of the Dc2 consumer once i failback.

I can confirm that this strategy generally works. It is the first time though, that i see this behaviour.

**Comment by MaximGurschi** [comment]
Some more details. If i start another process to read from that topic (ABC) from **Dc1** then it gets the messages. It is just that process that is stuck.

If i can trust the symbol files i used it looks like in SafeKafkaHandle.ConsumerPoll, LibRdKafka.consumer_poll(handle, timeoutMs) always returns IntPtr.Zero.

**Comment by MaximGurschi** [comment]
I'm seeing that OnPartitionsRevoked is triggered during failback? What exactly does this mean and what should i do about it?

**Comment by MaximGurschi** [comment]
Ok i think i have the answer. Please confirm if this is correct Andreas.

I should perform an assign in OnPartitionsRevoked just as i do one in OnPartitionsAssigned. Is that correct?

**Comment by ah-** [comment]
Yes, you're right. See https://github.com/edenhill/librdkafka/blob/master/src/rdkafka.h#L875, OnPartitionsAssigned is the rebalance callback.

And I haven't forgotten about your PR, just need to find some time.

**Comment by MaximGurschi** [comment]
Thank you!

**Comment by MaximGurschi** [comment]
Actually looks like something else is going on. Even though in "OnPartitionsRevoked" i do:

Console.WriteLine($"Assigned partitions: [{string.Join(", ", partitions)}], member id: {consumer.MemberId}");
    var fromBeginning = partitions.Select(p => new TopicPartitionOffset(p.Topic, p.Partition, Offset.Beginning)).ToList();
    Console.WriteLine($"Updated assignment: [{string.Join(", ", fromBeginning)}]");
    consumer.Assign(fromBeginning);

, (as you have suggested in #22) it is not reliable. The consumer just sits without getting any messages.

Is there a reliable way to force the consumer to get messages if there was a "OnPartitionsRevoked" event for the connection?

**Comment by MaximGurschi** [comment]
What really puzzles me is why does the OnPartitionsRevoked get invoked at all.

My consuming application generates a unique (GUID) consumer group name. Why would partitions be revoked if the app is the only one in its group?

**Comment by MaximGurschi** [comment]
For reference, have asked Eden about this:
https://github.com/edenhill/librdkafka/issues/764
