### ISSUE TITLE
Add support for breaking out of the loop in Handle.Dispose

### ISSUE THREAD

**Issue by MaximGurschi** [ah-/rdkafka-dotnet#58]
Hello Andreas,

Would you consider adding support to break out of the following loop in Handle.Dispose(bool):
               while (OutQueueLength > 0)
                {
                    handle.Poll((IntPtr) 100);
                }

This is to not end up in the Dispose call blocking indefinitely if the cluster is down.

**Comment by ah-** [comment]
This is related to https://github.com/edenhill/librdkafka/issues/764#issuecomment-242573662?
It seems that the cleaner solution would be to solve the underlying issue in librdkafka to make OutQueueLength go down to 0.

A timeout for shutting down would probably make sense, but doesn't quite fit with the IDisposable interface and would mean that you could end up with an undefined state even after calling Dispose.

**Comment by MaximGurschi** [comment]
Hello Andreas, yes as you have worked out it is related. I have yet to find out an answer if the loop is supposed to run forever under such circumstances. If it is, then perhaps allowing a cancellation token to be injected into the handle (constructor) would make sense?

**Comment by MaximGurschi** [comment]
Maybe this needs to be closed indeed as there looks to be an underlying problem with librdkafka.
