### ISSUE TITLE
Support for Kafka Streams

### ISSUE THREAD

**Issue by robvanpamel** [ah-/rdkafka-dotnet#67]
Hi, 

Is there any support in the pipeline for processing Kafka Streams (eg [https://github.com/apache/kafka/blob/trunk/streams/examples/src/main/java/org/apache/kafka/streams/examples/wordcount/WordCountProcessorDemo.java] )? 

Kind regards

**Comment by ah-** [comment]
I'd love to see that but it doesn't exist yet. You could do something similar by just implementing the same patterns yourself, the general model definitely works.

I'm not actively working on it but contributions are definitely welcome.
