### ISSUE TITLE
Kafka Consumer cannot get Config.

### ISSUE THREAD

**Issue by snwfog** [ah-/rdkafka-dotnet#71]
Description
===========

I have a consumer trying to consume from a Kafka broker. Using new consumer API. But the second debug log is not printing and consumer hang indefinitely at `new Config`.

How to reproduce
================

```  
DebugLog($"Ingester service: grabbing kafka config {ConsumerGroupId}, and {StatisticsInterval}");
var config = new Config { GroupId = ConsumerGroupId, StatisticsInterval = StatisticsInterval };
config["debug"] = "broker,topic";
DebugLog($"Ingester service: starting with configuration [{string.Join(";", config.Dump())}], topic(s): [{string.Join(";", TopicNames)}]");
```

Checklist
=========
Please provide the following information:

 - [x] librdkafka version (release number or git tag): 9.1
 - [x] Apache Kafka version: 0.10.0.0
 - [x] librdkafka client configuration: As above
 - [x] Operating system: Window
 - [x] Using the legacy Consumer: No
 - [x] Using the high-level KafkaConsumer: Yes
 - [x] Provide logs (with `debug=..` as necessary) from librdkafka: No log, as it never pass `new Config`.
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by ah-** [comment]
Did you figure this out?
