### ISSUE TITLE
Code from the example on the main page is not compliling

### ISSUE THREAD

**Issue by KokaChernov** [ah-/rdkafka-dotnet#72]
In the consumer example usage need to change line
`consumer.Subscribe(new []{"testtopic"});`
for 
`consumer.Subscribe(new[] { "test" }.ToList());`

**Comment by ah-** [comment]
Ah, this must have changed since then. Want to send a pull request?

**Comment by treziac** [comment]
It's actually correct on master (with the ICollection change it works) but not on tag 0.9.1, which version should the home (master) readme reflect?

**Comment by ah-** [comment]
0.9.2 build is now up for testing which means the example works, final version will be pushed in a day or two.
