### ISSUE TITLE
Benchmark console app declares numThread variable, but usage is wrong

### ISSUE THREAD

**Issue by KokaChernov** [ah-/rdkafka-dotnet#74]
Variable:
` int numThreads = 1;`
later we declare that `numMessages * numThreads` have been sent:
` Console.WriteLine($"Sent {numMessages * numThreads} messages in {stopwatch.Elapsed}");`

Try setting `numThreads  `to anything but `1` and report would be wrong as we never really use that variable anywhere except the message counter formula. In fact we only emit `numMessages ` of messages, not `numMessages * numThreads` , and we dont spread multiple threads for it (at least I cant see it in the code). 
So either remove the useless variable or introduce multithreading the way it was conceived by the author.

**Comment by ah-** [comment]
Thanks, I've removed it.
