### ISSUE TITLE
Error: The requested operation cannot be performed on a file with a user-mapped section open.

### ISSUE THREAD

**Issue by Disamis** [ah-/rdkafka-dotnet#76]
I have played with enabling SSL on Windows 7 by link  https://github.com/edenhill/librdkafka/wiki/Using-SSL-with-librdkafka, changed server.properties file, then got error on starting kafka: The requested operation cannot be performed on a file with a user-mapped section open.
I rollbacked changes but error is still here. I even unpack new version of kafka in another folder, but still have the same issue.

**Comment by ah-** [comment]
Is this a broker error? Try https://kafka.apache.org/contact, this is the issue section for the C# client only, I have no experience running a broker on Windows.
