### ISSUE TITLE
Expose librdkafka 0.9.2

### ISSUE THREAD

**Issue by MaximGurschi** [ah-/rdkafka-dotnet#80]
Hello Andreas, what are your plans to release the updated engine under RdKafka .NET?

**Comment by ah-** [comment]
There's a build up on nuget. Please test, once I'm somewhat certain it works fully I'll put it up as a release.

**Comment by MaximGurschi** [comment]
Thanks Andreas. Will experiment with it too!

**Comment by schaab** [comment]
@ah- Have you had success with receiving messages when you subscribe to a non-existing topic?

**Comment by ah-** [comment]
No idea, maybe ask @edenhill.

**Comment by edenhill** [comment]
@schaab That'll work when the topic is eventually created and then within topic.metadata.refresh.interval.ms (for the consumer to pick up on the now existing topic).

**Comment by schaab** [comment]
Thanks @edenhill. Are there any performance implications if we lowered that from 300000ms to say 10000?

**Comment by edenhill** [comment]
Depends on the topic count in your cluster, try the new value but monitor broker CPU stats

**Comment by schaab** [comment]
@ah- is regex\wildcard support in this release as implied by #55?

**Comment by ah-** [comment]
I think so, give it a try.
