### ISSUE TITLE
Allow specifying a segment of the payload for produce

### ISSUE THREAD

**Issue by MaximGurschi** [ah-/rdkafka-dotnet#81]
Hello Andreas,

Would you consider a pull request that allows specifying a segment of the payload bytes to send?
This is to avoid buffer copying. It will require some unsafe code though.

**Comment by ah-** [comment]
Good timing. There was/is a PR implementing exactly that: https://github.com/ah-/rdkafka-dotnet/pull/79 and https://github.com/ah-/rdkafka-dotnet/pull/73

I'll have a look as soon as a find some time, if you test it it'll certainly go in quicker.

**Comment by MaximGurschi** [comment]
Happy to test.

**Comment by MaximGurschi** [comment]
Are you waiting for me to test the PR before implementing this?

**Comment by ah-** [comment]
Hi, I'm just waiting to have some time to do some minimal sanity checks. If you have time please test, that'll speed things up.
