### ISSUE TITLE
Producing from ASP.Net apps

### ISSUE THREAD

**Issue by TobbenTM** [ah-/rdkafka-dotnet#83]
I'm having some issues using the Producer from an ASP.Net webapp, and I'm wondering if anyone has any experience or tips on how to solve.

I've created a simple ASP.Net producer here: https://github.com/TobbenTM/rdkafka-dotnet/tree/master/examples/SimpleWebProducer

It's basically the SimpleProducer example stuck inside a controller. 
To reproduce the exception, hit the /api/produce endpoints multiple times until failure (usually just spam F5 ~10 times).

In my environment, all the other examples work, even the benchmarking with >400k produced per second, but the ASP.Net example fails with TaskCanceledException:

```
System.AggregateException was unhandled by user code
  HResult=-2146233088
  Message=One or more errors occurred. (A task was canceled.)
  Source=System.Private.CoreLib
  StackTrace:
       at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
       at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
       at System.Threading.Tasks.Task.Wait()
       at RdKafka.Handle.Dispose(Boolean disposing) in ...\rdkafka-dotnet\src\RdKafka\Handle.cs:line 81
       at RdKafka.Handle.Dispose() in ...\rdkafka-dotnet\src\RdKafka\Handle.cs:line 74
       at SimpleWebProducer.Controllers.ProduceController.Produce() in ...\rdkafka-dotnet\examples\SimpleWebProducer\Controllers\ProduceController.cs:line 29
       at lambda_method(Closure , Object , Object[] )
       at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionFilterAsync>d__28.MoveNext()
  InnerException: 
       HResult=-2146233029
       Message=A task was canceled.
       InnerException:  
```

Am I doing something really wrong, or is this another issue?

Happens on both 0.9.1 and 0.9.2-ci-179.

**Comment by ah-** [comment]
Does it work if you keep the producer/topic alive? Creating it once and then injecting it into the controller?

I'll give it a try but I think it's because the producer is shut down before the message is even fully sent. The way it complains about that might need improving though.

**Comment by TobbenTM** [comment]
Yeah, that was my initial hunch as well, but as I understood it, disposing the producer should block until all messages are sent? Which means ASP.Net shouldn't really kill it (yet). 

But I'll try your suggestion more completely tomorrow, we are already doing something similar, having a singleton calling it (which has the same problem).

**Comment by ah-** [comment]
Can you reproduce it with just kestrel, without IIS?
I don't have an IIS setup and can't reproduce it with just kestrel, it just works for me.

That said, after having another look I do suspect there's a TaskCanceledException that needs to be handled, possibly around https://github.com/TobbenTM/rdkafka-dotnet/blob/master/src/RdKafka/Handle.cs#L81.

If you find what it is please send a PR. There's not much happening in the Callback loop at https://github.com/TobbenTM/rdkafka-dotnet/blob/master/src/RdKafka/Handle.cs#L159 that's most likely throwing this, not sure how that would be throwing that exception.

**Comment by TobbenTM** [comment]
Alright, think I got it working, still haven't managed to reproduce it. 

Followed your suggestion of letting ASP.Net control the lifecycle, and comitted my working solution to the example repo (https://github.com/TobbenTM/rdkafka-dotnet/tree/master/examples/SimpleWebProducer).

I'll close this for now, and if I find a better way, or end up fixing the TaskCanceledException I'll submit a pr. 

Thanks!
