### ISSUE TITLE
How to serialize message using Apache AVRO with rdkafka-dotnet

### ISSUE THREAD

**Issue by vungoctho** [ah-/rdkafka-dotnet#85]
Hi, I have just started using this library. I can not find any documentation/configuration that show how to use Kafka Avro Serializer when produce/assign the message to partition.
Can you please help me out if this library support the Kafka Avro Serializer ?

**Comment by ah-** [comment]
Hi, 

This Library doesn't include an avro serialiser, but you can plug in your own. I think there's a C# Avro library.

**Comment by vungoctho** [comment]
Hi AH, thanks for your quick answer.

**Comment by treziac** [comment]
I do it using the Microsoft azure avro library (old version which included avro support) with some modif (.net core support and some missing functionalities like default value, etc), didn't try the C# avro library (missing doc/empty website). It's fully working with confuent schema registry
Not sure I can open-source it as it's part of my work, but will be glad to do it if possible :)

**Comment by vungoctho** [comment]
Hi, actually there are some C# Avro libraries to help serialize/deserialize data. And I'm also going to use Microsoft Azure Avro lib (package name is Microsoft.Hadoop.Avro v1.5.6) in my project. Hope you can share some experiences on it.

**Comment by nathanyeung** [comment]
Which library did you guys end up picking for Avro?

**Comment by treziac** [comment]
I'm still using the microsoft library with some modifs (which i haven't repushed on github)
You can also look here: https://github.com/jakobz/schema-registry-dotnet
If you use confluent schema registry, it will be useful. This one use the Avro library (from apache), so you will have some base to start with

**Comment by vungoctho** [comment]
Hi,
I'm using the Microsoft.Hadoop.Avro nuget package for Avro serializing

**Comment by simplesteph** [comment]
@treziac any chance of open-sourcing the serializer / deserializer for avro / confluent schema registry? It'd be good to include that in https://github.com/confluentinc/confluent-kafka-dotnet

**Comment by treziac** [comment]
I might one day, but don't have time for now
Did you try the other project I mentionned? (https://github.com/jakobz/schema-registry-dotnet)
It uses the Apache Avro .NET Library and not the microsoft one but should work :)
