### ISSUE TITLE
Does rdkafka-dotnet support lz4 compression?

### ISSUE THREAD

**Issue by wuyuntao** [ah-/rdkafka-dotnet#90]
An InvalidOperationException is thrown when I set `compression.codec` = `lz4`. `gzip` and `snappy` works well though.

**Comment by ah-** [comment]
Can you try the 0.9.2 preview build? That might have it enabled.

**Comment by wuyuntao** [comment]
No luck with 0.9.2 preview build. lz4 support of Win32 platform was added to librdkafka after 0.9.2. So I suppose I can either build with the latest librdkafka or just wait for the next release :-)
