### ISSUE TITLE
Thread affinity of the EventConsumer

### ISSUE THREAD

**Issue by MaximGurschi** [ah-/rdkafka-dotnet#94]
Hello Andreas,

Hopefully a simple one for you.
Can we rely on the OnMessage callback of the EventConsumer to always be invoked sequentially (as long as i do not stop/start in sequence)?
I know the librdkafka threading model suggests that. I just want to confirm what assumptions i can make in my code.

**Comment by treziac** [comment]
Yes:
- no async call, Start in eventConsumer is monothreaded and delegate are called synchronously
- offset will always be sequential for two message from same partitions

**Comment by MaximGurschi** [comment]
Thanks for confirming the contract.
