### ISSUE TITLE
librdkafka DllNotFoundException  in Windows server 2012

### ISSUE THREAD

**Issue by Tharunkumar** [ah-/rdkafka-dotnet#95]
Hi Team,

I am currently using RDkafka version 0.9.1.0 and .netcore '1.0.0-preview2-1-003177' version. When i am deploying the application in my local IIS(Windows 8) it is working fine.Whereas when i put the same artifacts in a server machine IIS(Windows server 2012 R2 OS installed) , I am getting DLL not found exception for librdkafka. Is this issue related to librdkafka dll not available in any specific runtime . If so can you please let me know what is the run time for Windows server 2012 R2?

The runtimes that i have currently is attached in the below image.

![image](https://cloud.githubusercontent.com/assets/2314442/21045761/a273a5c6-be27-11e6-9ee6-e6d1e0eaa6dc.png)

dotnet --info output of my localmachine 
![image](https://cloud.githubusercontent.com/assets/2314442/21046549/3b95ac7e-be2b-11e6-983f-7af98d425d86.png)

dotnet --info output of server machine which has windows server R2 installed

![image](https://cloud.githubusercontent.com/assets/2314442/21046572/5c1bc050-be2b-11e6-9b71-f7971e49c4df.png)

**Comment by treziac** [comment]
Is this this error?
https://github.com/ah-/rdkafka-dotnet/wiki/Faq#how-can-i-fix-hresult0x8007007e-exception-during-librdkafka-initialization-on-production-server

**Comment by treziac** [comment]
Also if it said you miss librdkafka.dll, check that you have folders x86/x64 in your artifacts, with librdkafka.dll and zlib.dll inside

**Comment by Tharunkumar** [comment]
@treziac , i checked win7-x64 and x86 folders. Both librdkafka.dll and zlib.dll are available in that directory.
What i am suspecting is for window server 2012 r2 do we need a different runtime like win81-x64 or something? But still my machine in Win8.

**Comment by treziac** [comment]
It's the same RID for both, so not a platform problem i think

Did you look at https://github.com/ah-/rdkafka-dotnet/wiki/Faq#how-can-i-fix-hresult0x8007007e-exception-during-librdkafka-initialization-on-production-server ? (ie install Visual C++ Redistributable Packages for Visual Studio 2013 on production server - this must be this exact version) or can you copy the complete error message?

**Comment by ah-** [comment]
I strongly suspect it's the missing redist.

**Comment by Tharunkumar** [comment]
@treziac : Thanks, Installing VS 2013 C++ Redistributable solved this issue.

**Comment by YosefFixler** [comment]
Hi,
Is there any reason VS 2013 C++ Redistributable package is required specifically?
Why VS 2015 C++ Redistributable package cannot do the work?
We have the 2015 version installed at our production machines.

**Comment by ah-** [comment]
It is compiled with VS 2013, so it needs the matching redistributable. Ideally this would be solved by just statically linking though.
