### ISSUE TITLE
Retry mechanism on Kafka

### ISSUE THREAD

**Issue by vungoctho** [ah-/rdkafka-dotnet#98]
Hi,
As I see, if the Transport connection error (broker list is down), the Producer & Consumer will retry to re-connect internally (with n-times) .
So if there is exception error during processing the message (e.g. persist data to DB timeout, or invoke 3rd Service error), does the library retry to re-read this message in n-times automatically? Or I need to handle it manually?
Thanks

**Comment by MaximGurschi** [comment]
If you are using the EventConsumer the consumer thread will stop processing messages on an exception. You should handle any exceptions in the callback.

If you are using the simple consumer then the polling call is not affected by "outside" exceptions.

**Comment by ah-** [comment]
Hi, 

exactly what Maxim said. Within the process you need to handle message processing retries yourself, once the callback returns rdkafka assumes you have successfully processed the message.

**Comment by vungoctho** [comment]
Thank you for your answer!
